version: '{build}'

environment:
  matrix:
  - CONFIGURATION: Debug
  - CONFIGURATION: Release

install:
- git submodule update --init --recursive
- appveyor DownloadFile http://www.secfs.net/winfsp/resources/Test.Filter.Driver.zip & 7z x Test.Filter.Driver.zip
- appveyor AddMessage "Change boot configuration and reboot" -Category Information
- if exist %SystemRoot%\memory.dmp del %SystemRoot%\memory.dmp
- verifier /standard /driver winfsp-x64.sys
- bcdedit /set testsigning on
- ps: Restart-Computer -Force
- ps: Start-Sleep -s 60

build_script:
- appveyor AddMessage "Reboot complete" -Category Information
- bcdedit | findstr /i "testsigning"
- tools\build.bat %CONFIGURATION%

test_script:
- for %%f in ("build\VStudio\build\%CONFIGURATION%\winfsp-*.msi") do start /wait msiexec /i %%f /qn INSTALLLEVEL=1000
- start /wait msiexec /i "Test.Filter.Driver\HCK Filter.Driver Content-x86_en-us.msi" /qn
- tools\nmake-ext-test.bat %CONFIGURATION%
- tools\run-tests.bat %CONFIGURATION%
- tools\run-tests.bat %CONFIGURATION% ifstest
- if exist %SystemRoot%\memory.dmp exit 1

on_finish:
- if exist %SystemRoot%\memory.dmp (7z a memory.dmp.zip %SystemRoot%\memory.dmp & appveyor PushArtifact memory.dmp.zip)
- verifier /query
